

function StudentDashboard() {
  return(
    <> 
     <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo reiciendis earum magnam rem aliquid accusamus laboriosam, modi velit molestias! Soluta id maxime magni voluptas? Magni facilis pariatur deserunt ipsa quibusdam.
     Sequi rerum error voluptas fuga quasi ad ipsa voluptatem quod ducimus, nisi tempore quisquam perspiciatis fugiat culpa provident quo, placeat cum obcaecati quibusdam ut iste mollitia laborum ipsum exercitationem. Inventore.
     Esse vero ea error expedita cum assumenda dicta magnam? Non velit porro debitis nesciunt dolore, eaque sed laudantium possimus, corporis reiciendis quae pariatur eius ex eos expedita sit magni libero?
     Velit enim quidem sit consectetur commodi quae. Quas ex iusto quis eveniet dignissimos sequi impedit animi exercitationem magnam error. Labore beatae quam vel maiores eveniet facere porro architecto facilis tempore.
     Alias quos temporibus aperiam iste tempore est, aut consequuntur ut quidem placeat aspernatur incidunt fuga officiis dolore expedita sed perferendis dolor autem inventore ullam. Cupiditate exercitationem eveniet ipsum laboriosam rerum!
     Nobis quasi quidem aliquid exercitationem hic libero? Molestiae consequuntur eligendi, impedit rerum laboriosam perspiciatis fugiat error alias corporis optio cupiditate dolorum odit sed? Nostrum tenetur ex molestiae aperiam, alias voluptates.
     Cupiditate, architecto ullam quam itaque, dolores pariatur quis accusantium inventore accusamus dolore totam sit hic asperiores repellat. Illum, dignissimos totam maiores odio perferendis ea ipsa adipisci, excepturi expedita, fuga praesentium!
     Vero a quam, animi obcaecati repudiandae laudantium sed, minus porro maiores minima consectetur quae tempore excepturi cum nobis quas blanditiis veritatis mollitia. Fugiat, ut et at blanditiis molestias voluptatem dolores.
     Explicabo architecto nostrum accusantium ad nemo reprehenderit numquam, impedit assumenda corrupti! Laborum ea ipsum illum veritatis quae libero quia obcaecati voluptatum esse dolorum nulla quod blanditiis, modi quas exercitationem impedit.
     Iusto praesentium dolor fugiat hic cumque quo, consequuntur molestiae, tenetur temporibus voluptatibus harum error ut inventore odio vitae suscipit impedit maxime dignissimos libero delectus eos aspernatur? Hic quae tempore culpa!
     Corrupti ducimus assumenda voluptatibus harum voluptatem quidem. Tempora nam libero maxime suscipit corrupti, eum qui, facilis possimus quos molestias ipsum cupiditate nesciunt minus repellendus sint vel commodi mollitia. Excepturi, voluptatum?
     Deleniti officia pariatur dolore velit, veniam tenetur beatae facilis odio, ipsa maiores facere debitis ducimus labore dicta dolores iusto? Accusantium voluptate saepe suscipit laborum soluta velit consequatur tempora, quos at!
     Alias, labore. Aspernatur totam doloremque, ratione eos voluptatum vero ipsa expedita magnam deserunt placeat cupiditate nihil! Vero quas fugit id blanditiis neque sint quod pariatur, vel ex sapiente incidunt perferendis.
     Expedita repellat quos excepturi nesciunt reprehenderit totam reiciendis rem, fuga nisi eligendi. Voluptas, atque rerum beatae ratione repellendus dolore laudantium ipsa labore ullam voluptatibus provident vel blanditiis iure aliquid aspernatur.
     Repellat, quod hic nulla blanditiis consequuntur veritatis eius dolores quas quo numquam? Amet sunt officiis praesentium exercitationem doloribus dolorem cupiditate error, necessitatibus velit minus modi eligendi expedita sit? Veniam, atque.
     Quasi molestiae voluptatibus dolor dolore aspernatur quia dolores quod vero tempore, repellat magnam cum voluptatum hic illum ullam facere alias voluptates quos non. Cupiditate eligendi dicta architecto, enim perspiciatis ratione.
     Perferendis doloremque quae repellendus libero perspiciatis mollitia autem dolor reprehenderit hic, sunt recusandae harum, iusto necessitatibus accusantium repudiandae. Aliquid ea voluptatum, fuga natus dolore totam praesentium placeat eos dignissimos voluptas?
     In nesciunt alias libero numquam unde molestias tempore iste similique quae dolores, quis doloribus error veritatis cum doloremque provident obcaecati animi quas a ea vero accusamus ipsum facilis consequuntur! Temporibus.
     Asperiores cupiditate voluptatem similique architecto, placeat quidem molestiae deserunt maiores totam tenetur illo a modi quo iste labore ea assumenda blanditiis non porro obcaecati! Nobis dolorem sapiente neque soluta qui?
     Amet, aliquam cupiditate consectetur nesciunt dicta soluta perspiciatis quasi praesentium officia aliquid nemo fuga, laudantium nisi iusto, beatae nobis distinctio. Labore a maiores esse officiis repellendus similique nam autem hic!
     Sequi rerum ipsum vitae cum doloremque eaque unde? Nihil dolorum illo est et alias beatae unde delectus quibusdam accusantium, ut voluptas laboriosam cumque minus, eum quisquam aspernatur placeat provident suscipit.
     Dolor nemo quisquam, vitae nulla ducimus aperiam aliquam porro reprehenderit nam, esse, a culpa aut consectetur. Doloremque quasi quos possimus corporis facilis repellendus inventore aliquid beatae vel, itaque alias deserunt!
     Ipsum architecto excepturi repudiandae quae, eligendi officia non numquam placeat doloribus molestiae minus ad consectetur, veniam unde voluptatum recusandae aut tempore id. Aliquam nisi alias facilis at culpa nam cumque?
     Commodi, eos molestias enim molestiae nesciunt quidem eum iusto adipisci praesentium magnam. Adipisci, aliquid at. Error delectus magni minima maiores aspernatur aut hic cum, ipsum reprehenderit suscipit numquam explicabo quidem.
     Ut iure eligendi eveniet commodi ipsa vero in natus eius, deleniti laboriosam? Animi accusamus quia earum. Illum corporis sint quo necessitatibus tempora tenetur, voluptas doloremque pariatur sequi atque voluptates quaerat.
     Dolorem maxime aperiam velit officia corrupti amet, quasi ea beatae animi, cupiditate ex cumque? Fugiat nulla error labore exercitationem officiis voluptates non illo cupiditate quidem. Ex laudantium similique laborum nostrum!
     Iusto reprehenderit et autem maxime, laborum ullam provident perferendis amet aut laboriosam asperiores deserunt laudantium consectetur perspiciatis explicabo illum delectus, tempore ea adipisci eaque? Iste voluptatum nostrum animi aliquam magnam!
     Doloribus, ut optio at eum quos cum laudantium ipsam id autem mollitia qui aut tenetur ipsa sapiente, quaerat dolorem veritatis itaque velit maiores nihil accusamus perferendis commodi? Accusantium, velit minima?
     Tenetur adipisci dolorem sed beatae ex nesciunt odit impedit nam sit nobis eum dolores debitis sequi iste fugit a dicta aperiam quasi amet, veritatis hic eos necessitatibus voluptatem culpa? Sequi!
     Enim ullam praesentium veritatis nam assumenda quas possimus ex vel culpa illo inventore expedita nisi nihil ad quidem deserunt dignissimos, dolore aut suscipit labore cupiditate cumque, animi aperiam. Rerum, error?
     Distinctio, nemo? Illo quae ex sequi qui quidem magni possimus dolorum perferendis harum explicabo, temporibus deserunt reiciendis atque unde reprehenderit voluptatibus exercitationem suscipit aut minima cum ipsa! Unde, asperiores officiis!
     Ipsum sunt, excepturi nihil fugit nesciunt voluptatem temporibus ullam similique ducimus voluptates a soluta maxime aliquid voluptas aliquam obcaecati possimus sit debitis dolore. Voluptatem ut in dolor eum impedit iste?
     Facilis laborum nulla, culpa debitis fuga quis doloribus quam quo nihil illo? Voluptatibus perferendis, ratione fuga placeat quas porro? Sequi dolor harum illum voluptates praesentium veritatis culpa commodi non at.
     Sapiente quo nulla, enim neque architecto delectus rerum similique quisquam error eligendi expedita iure quam sint et eaque incidunt mollitia aperiam praesentium nemo blanditiis perspiciatis dolorum quidem aut accusamus? Voluptates.
     Eveniet tenetur ducimus nobis iure! Mollitia quos voluptate ea nulla fugit? Culpa nobis eligendi dolorum voluptatibus quos doloribus harum ad inventore, numquam aut excepturi reiciendis? Fuga, veritatis. Sed, ut ipsam.
     Consequuntur omnis saepe cupiditate ab ducimus ullam, tempore iure voluptate sunt aliquam deleniti accusantium culpa maiores commodi iste facilis? Dolorem ut nostrum nobis! Quam exercitationem tenetur ipsa at quidem libero?
     Illum laboriosam tempore dolorem facilis recusandae cumque tempora omnis consequatur! Facere dolor debitis nostrum doloribus aliquam porro ratione, pariatur harum culpa iste commodi distinctio maiores ea voluptatem, laudantium fugiat dicta!
     Consequatur possimus distinctio totam, vero iste pariatur rem vel sunt deserunt eos voluptatum ab quasi optio impedit sed! Eius sit provident tempore suscipit eum quia quibusdam ad dolores unde cumque.
     Culpa expedita, iure deleniti necessitatibus quibusdam ad quasi corrupti itaque atque, ipsam vitae omnis consequuntur suscipit commodi, reiciendis numquam? Labore harum excepturi quia libero suscipit impedit, nulla adipisci voluptatem ab!
     Veritatis consequatur eveniet natus deleniti, facilis ea at ad, delectus earum, nulla a? Ut facilis omnis, repellat enim nihil facere, fugit sapiente quidem atque minima, suscipit nesciunt excepturi perspiciatis esse?
     Temporibus earum eveniet perspiciatis dolor nobis in consequatur ex mollitia culpa porro, repudiandae voluptatum quia deserunt error magni labore voluptas ratione praesentium commodi, corrupti dicta rerum nemo? Libero, et beatae.
     Corporis perspiciatis esse obcaecati officia odit molestias quis soluta, distinctio natus vel? Sunt molestiae minima quod odio enim provident nemo repellendus incidunt ipsa! Quae repellendus consequuntur quaerat dolor nesciunt harum!
     Mollitia voluptatum excepturi inventore doloribus alias debitis quibusdam exercitationem quos nostrum modi expedita eveniet ea, cumque aperiam possimus delectus corporis maxime quisquam fugiat in rerum magni itaque, distinctio dolor. Aliquam.
     Nulla velit quae reiciendis id a numquam, ex, voluptatem eligendi obcaecati adipisci animi sit eaque maxime natus quos, accusamus minus recusandae laudantium necessitatibus nemo harum. At animi minus rem blanditiis!
     Sunt, totam id officia eos exercitationem quisquam quis, quod accusamus minus temporibus delectus! Ullam eveniet beatae necessitatibus, qui praesentium aperiam sunt eius molestiae amet enim eum magnam asperiores corporis soluta.
     Aliquid animi dolorem nostrum fugiat voluptates accusantium doloribus eum molestias quidem sint! Explicabo quo voluptatem quaerat iste, architecto fugiat quisquam dolores praesentium, culpa velit quam voluptatum nesciunt consequuntur ab voluptas.
     Saepe expedita provident exercitationem accusamus repudiandae voluptas sit rem nihil aspernatur veniam error pariatur dolorum tempora quod quo nulla neque cupiditate, in sequi deserunt, quae optio unde ab! Recusandae, illum.
     Repellendus praesentium quam nemo provident repudiandae, nam ipsam unde dolorem, tempora magnam ea et mollitia voluptatibus commodi accusamus corrupti deserunt quas nesciunt dolore voluptas atque laborum consectetur? Nisi, laudantium odit?
     Deserunt tempora optio reiciendis ab ea, perspiciatis sint. Vitae veritatis illo quaerat? Cupiditate consequuntur nobis sint doloribus incidunt dolores, eos voluptas quo architecto tempore amet omnis a? Quas, natus adipisci.
     Magnam reiciendis placeat praesentium totam minus iure, consequatur illum quibusdam laudantium, dignissimos nemo. Quaerat sequi odit voluptates. Molestiae animi laboriosam corporis labore, cupiditate quo magni, unde voluptates minima eius deserunt.</h1>
    </>
  )
}

export default  StudentDashboard;